"""add table order order_detail

Revision ID: 06113fc9ec2b
Revises: 7aad64a27bcc
Create Date: 2024-05-12 15:19:38.205263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06113fc9ec2b'
down_revision = '7aad64a27bcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customerId', sa.Integer(), nullable=False),
    sa.Column('fullName', sa.String(length=256), nullable=False),
    sa.Column('addressId', sa.Integer(), nullable=False),
    sa.Column('paymentMethod', sa.Enum('COD', 'BANKING', name='paymentmethodenum'), nullable=False),
    sa.Column('paymentStatus', sa.Enum('PAID', 'UNPAID', name='paymentstatusenum'), nullable=False),
    sa.Column('note', sa.String(length=256), nullable=True),
    sa.Column('status', sa.Enum('PAID', 'UNPAID', name='paymentstatusenum'), nullable=False),
    sa.Column('shippingName', sa.String(length=256), nullable=False),
    sa.Column('shippingCode', sa.String(length=256), nullable=False),
    sa.Column('totalAmount', sa.Integer(), nullable=False),
    sa.Column('isDeleted', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['addressId'], ['address.id'], ),
    sa.ForeignKeyConstraint(['customerId'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('orderId', sa.Integer(), nullable=False),
    sa.Column('productId', sa.Integer(), nullable=False),
    sa.Column('variationId', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('oldPrice', sa.Integer(), nullable=False),
    sa.Column('isDeleted', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['orderId'], ['order.id'], ),
    sa.ForeignKeyConstraint(['productId'], ['product.id'], ),
    sa.ForeignKeyConstraint(['variationId'], ['variation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_detail')
    op.drop_table('order')
    # ### end Alembic commands ###
