"""modify table order

Revision ID: 1bc1da10596f
Revises: 812d98c1b9d3
Create Date: 2024-05-19 01:49:19.720034

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1bc1da10596f'
down_revision = '812d98c1b9d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=256), nullable=False))
        batch_op.alter_column('orderDate',
               existing_type=mysql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('orderDate',
               existing_type=mysql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_column('email')

    # ### end Alembic commands ###
