"""modify table rating

Revision ID: 3b528a44b589
Revises: d8bc71aac8f7
Create Date: 2024-05-14 22:28:10.246114

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3b528a44b589'
down_revision = 'd8bc71aac8f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orderDetailId', sa.Integer(), nullable=True))
        batch_op.drop_constraint('rating_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('rating_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'order_detail', ['orderDetailId'], ['id'])
        batch_op.drop_column('productId')
        batch_op.drop_column('variationId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variationId', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('productId', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('rating_ibfk_2', 'product', ['productId'], ['id'])
        batch_op.create_foreign_key('rating_ibfk_3', 'variation', ['variationId'], ['id'])
        batch_op.drop_column('orderDetailId')

    # ### end Alembic commands ###
