"""modify table order add orderDate

Revision ID: 473d32dbfd73
Revises: 93ae37429667
Create Date: 2024-05-15 22:17:07.766321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '473d32dbfd73'
down_revision = '93ae37429667'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orderDate', sa.TIMESTAMP(timezone=True), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('orderDate')

    # ### end Alembic commands ###
