"""modify table rating

Revision ID: 812d98c1b9d3
Revises: 473d32dbfd73
Create Date: 2024-05-16 22:35:37.771834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '812d98c1b9d3'
down_revision = '473d32dbfd73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variationId', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('productId', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'variation', ['variationId'], ['id'])
        batch_op.create_foreign_key(None, 'product', ['productId'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('productId')
        batch_op.drop_column('variationId')

    # ### end Alembic commands ###
