"""modify table token

Revision ID: 93ae37429667
Revises: d4d924906739
Create Date: 2024-05-15 17:53:18.357375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '93ae37429667'
down_revision = 'd4d924906739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.alter_column('uid',
               existing_type=mysql.VARCHAR(length=512),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.alter_column('token',
               existing_type=mysql.VARCHAR(length=512),
               type_=sa.String(length=2048),
               existing_nullable=False)
        batch_op.drop_index('uid')
        batch_op.create_foreign_key(None, 'customer', ['uid'], ['uid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('uid', ['uid'], unique=True)
        batch_op.alter_column('token',
               existing_type=sa.String(length=2048),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=False)
        batch_op.alter_column('uid',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=False)

    # ### end Alembic commands ###
