"""refactor table order

Revision ID: c91c82957d38
Revises: 50caaf16db93
Create Date: 2024-05-15 16:53:06.891354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c91c82957d38'
down_revision = '50caaf16db93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('SUCCESS', 'ORDER', 'CANCEL', 'SHIPPING', 'PREPARING', name='orderstatusenum'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
