"""refactor customer image

Revision ID: e66e51637fcb
Revises: 06113fc9ec2b
Create Date: 2024-05-12 15:31:54.083944

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e66e51637fcb'
down_revision = '06113fc9ec2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('productId', sa.Integer(), nullable=False))
        batch_op.drop_constraint('product_image_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'product', ['productId'], ['id'])
        batch_op.drop_column('product_id')

    with op.batch_alter_table('rating_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ratingId', sa.Integer(), nullable=False))
        batch_op.drop_constraint('rating_image_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'rating', ['ratingId'], ['id'])
        batch_op.drop_column('rating_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('rating_image_ibfk_1', 'rating', ['rating_id'], ['id'])
        batch_op.drop_column('ratingId')

    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('product_image_ibfk_1', 'product', ['product_id'], ['id'])
        batch_op.drop_column('productId')

    # ### end Alembic commands ###
